import fs from 'node:fs';
import {course as sourceCourse,topics} from './legacy-course.ts';
import {buildDeck} from './legacy-deck.ts';
const write=(path,data)=>fs.writeFileSync(path,JSON.stringify(data,null,2)+'\n');
const version='trzbd-2026.09.13-1';
const course={schemaVersion:1,contentVersion:version,id:'trzbd',code:'МДК.11.01 · 4 курс',discipline:'Технология разработки и защиты баз данных',year:'2026–2027',heroTitle:'Разрабатывайте и защищайте',heroAccent:'базы данных',slogan:'От исходных данных — к проверенной и защищённой базе',mascot:'brand/mascot/trzbd-database-rhino-catalog.png',mascotAlt:'Носорог — разработчик и защитник баз данных',logo:'brand/synergy-logo.png',ornament:'brand/side-ornament.png',font:'fonts/raleway-cyrillic.woff2',topicArrow:'brand/topic-arrow.webp',materialsUrl:sourceCourse.materialsUrl,demo:false,semesters:sourceCourse.semesters,assessment:{mode:'autonomous',url:'assessment.json'},lectures:[],glossary:[],curriculum:[]};
const first=buildDeck(topics[0],sourceCourse);
course.literature=Object.fromEntries(['primary','additional'].map((group,i)=>[group,first[i+2].bullets.map((citation,j)=>({citation,url:first[i+2].links[j].url}))]));
const notes={},keys={},questions=[],mapping=[],links={},registry=[];
const rotate=(xs,n)=>[...xs.slice(n%xs.length),...xs.slice(0,n%xs.length)];
for(const [li,t] of topics.entries()){
 const old=buildDeck(t,sourceCourse),slides=[];links[t.id]={};
 const id=name=>`${t.id}-${name}`;
 function add(slide,script,oldSlides=[],extra={}){
  slide={kicker:t.displayTitle,source:`Исходная лекция: ${t.sourceTitle}. MySQL 8.4; сравнение с PostgreSQL 18 отмечено отдельно.`,...slide};slides.push(slide);
  notes[slide.id]={script,preparation:'Учебная сеть сервисных центров; исходные формулировки сохранены из проекта. Использовать синтетические данные и отдельную учебную базу. '+(extra.preparation||''),notebook:slide.notebook||'Запись на этом слайде не обязательна; итог вопроса дан в блоке «Запишите».',questions:extra.questions||'',answer:extra.answer||'',estimatedSeconds:extra.estimatedSeconds||Math.max(25,Math.round(script.split(/\s+/).length/2)+(slide.kind==='example'?60:20))};
  for(const s of oldSlides){mapping.push({lectureId:t.id,oldSlide:s.number,oldTitle:s.title,newSlideIds:[slide.id],action:extra.action||'Перенесено в макет шаблона; добавлена контекстная заметка'});links[t.id][s.number]??=slide.id;}
 }
 add({id:id('title'),kind:'title',title:t.displayTitle,body:t.objective,bullets:old[0].bullets},`Сегодня изучаем тему «${t.displayTitle}». ${t.caseBrief} Результат занятия — ${t.projectArtifact}. ${t.diagnostic} Сначала разберём источники и маршрут занятия, затем последовательно проверим восемь вопросов. Указанные ${t.lectureHours} лекционных часа и компетенции ${t.competencies.join(', ')} сохранены из исходного проекта.`,[old[0]],{preparation:'Официальные часы сохранены из исходной конфигурации; повторная сверка с РПД отдельно отражена в отчёте. Время заметок — оценка, а не расписание.'});
 for(const [group,offset,title] of [['primary',2,'Основная литература'],['additional',3,'Дополнительная литература']]){
  course.literature[group].forEach((ref,i)=>add({id:id(`literature-${group}-${i+1}`),kind:'literature',readingGroup:group,references:[ref],title:i?`${title} · продолжение`:title},`Для темы «${t.displayTitle}» сохраняем источник из исходной лекции: ${ref.citation} По ссылке или QR-коду открывается карточка издания. Полный текст книги не включён в сайт; номера страниц не назначаем без сверки с изданием. ${group==='primary'?'Основная литература задаёт учебную основу понятий.':'Дополнительная литература позволяет сопоставить объяснения и практику SQL.'} Если пример использует PL/pgSQL, не переносим его синтаксис в MySQL: это разные процедурные языки. Далее ${i<course.literature[group].length-1?'следующий источник':group==='primary'?'дополнительная литература':'папка материалов курса'}.`,[old[offset]]));
 }
 add({id:id('materials'),kind:'materials',title:'Материалы к занятию'},`Папка материалов этого курса: ${course.materialsUrl}. Адрес сохранён из исходного проекта ТРЗБД. Открываем ссылку или сканируем QR-код; они ведут в одно место. Для сегодняшней темы ориентир — ${t.projectArtifact}. Состав папки может изменяться, поэтому конкретный файл выбираем по заданию и его версии. Следующий слайд показывает порядок вопросов.`,[old[4]]);
 add({id:id('agenda'),kind:'agenda',title:'Вопросы темы',kicker:'Карта темы'},`Маршрут занятия: ${t.questions.map((q,i)=>`${i+1}. ${q.title}`).join('; ')}. Эти вопросы приводят к результату «${t.projectArtifact}». После каждого вопроса есть проверка четырьмя типами заданий. Карта строится по разделителям, поэтому порядок здесь совпадает с последовательностью слайдов. Начнём с места темы в учебном проекте.`,[old[8]]);
 for(const index of [1,5,6,7,10,11]){
  const s=old[index];add({id:id(`intro-${s.number}`),kind:s.kind==='example'?'example':'theory',title:s.title,body:s.body,bullets:s.bullets},`${s.title}. ${s.body||''} ${(s.bullets||[]).join(' ')} В нашем случае это относится к следующему результату: ${t.projectArtifact}. ${t.diagnostic} Ответ должен связать исходные данные, проектное действие и способ проверки. Далее перейдём к ${index===11?'рабочему примеру SQL': 'следующему элементу вводной части'}.`,[s]);
 }
 const code=old[9];add({id:id('code'),kind:'example',title:code.title,body:code.body,visual:{type:'codeParts',parts:[{code:t.codeSample,label:t.codeLabel,explanation:t.objective}],caption:'Сохранённый учебный фрагмент. Для выполнения нужны подготовленные объекты и соответствующие права.'}},`Рассмотрим фрагмент «${t.codeLabel}»: ${t.codeSample} Его назначение — ${t.objective.toLowerCase()}. Имена объектов относятся к учебному стенду. ${code.body} После выполнения нужен фактический вывод, а не только отсутствие сообщения об ошибке. Критерии для содержательной проверки разберём в следующих вопросах.`,[code],{preparation:'Фрагмент сохранён из исходника. Наличие команды на слайде не подтверждает её запуск; требуемую схему и данные необходимо подготовить.'});
 for(const [qi,q] of t.questions.entries()){
  const qid=id(`q${String(qi+1).padStart(2,'0')}`),start=slides.length,block=old.filter(s=>s.questionNumber===qi+1);
  const next=t.questions[qi+1]?.title||'итоги занятия';
  const prev=t.questions[qi-1]?.title||'вводная часть';
  const qna=`Почему не подходит действие «${q.pitfall}»? Ответ: ${q.rule} Проверка: ${q.check}\nКак подтвердить решение «${q.decision}»? Ответ: ${q.check} Пример применения: ${q.example}`;
  add({id:qid+'-section',kind:'section',title:q.title,kicker:`Вопрос ${String(qi+1).padStart(2,'0')}`,body:q.focus},`После раздела «${prev}» переходим к вопросу «${q.title}». ${q.focus} На примере «${q.example}» рассмотрим, какое решение обосновано и чем его проверить. Итогом будет правило: ${q.rule} Сначала разберём смысл вопроса.`,[block[0]],{questions:qna});
  add({id:qid+'-concept',kind:'theory',title:block[1].title,body:q.focus,bullets:[q.rule,q.decision]},`${q.focus} Это объяснение нужно для конкретного проектного действия: ${q.decision} Исходная ситуация: ${q.example} В ней нельзя ограничиться названием объекта или фактом выполнения команды: ${q.check} Правило связывает действие с условиями — ${q.rule} Типичное затруднение состоит в том, чтобы ${q.pitfall.toLowerCase()} Далее покажем связь между исходными данными, правилом и результатом на схеме.`,[block[1]],{questions:qna});
  add({id:qid+'-rule',kind:'process',title:'Как получить проверяемый результат',visual:{type:'process',items:[{title:'Исходная ситуация',text:q.example},{title:'Правило действия',text:q.rule},{title:'Критерий проверки',text:q.check}],caption:q.focus}},`Схему читаем слева направо. На входе: ${q.example} Переход к действию выполняется по правилу: ${q.rule} Последний блок задаёт наблюдаемый критерий: ${q.check} Стрелки означают порядок обоснования решения; они не заменяют фактическую проверку. Если результат нельзя сопоставить с последним блоком, доказательство ещё не получено. Дальше развернём этот порядок применительно к исходному примеру.`,[block[2]],{questions:qna});
  add({id:qid+'-example',kind:'example',title:`Пример: ${q.title.toLowerCase()}`,body:q.example,steps:[{title:'Применяем правило',text:q.rule},{title:'Принимаем решение',text:q.decision},{title:'Проверяем результат',text:q.check}]},`Разбираем исходный пример: ${q.example} Сначала установим его смысл: ${q.focus} Теперь применим правило: ${q.rule} Получаем следующее проектное решение: ${q.decision} Его нельзя считать доказанным до проверки: ${q.check} Ошибочная ветвь — ${q.pitfall} Она не обеспечивает названный критерий. Здесь дан способ проверки, а не выдуманный вывод реально запущенной СУБД. Следующий слайд переносит этот разбор в практическое действие.`,[block[3]],{questions:qna,answer:q.decision+' '+q.check,estimatedSeconds:140});
  const practice=block.find(s=>s.kind==='practice');
  add({id:qid+'-practice',kind:'example',title:'Примените правило к учебному проекту',body:q.example,bullets:[`Действие: ${q.decision}`,`Доказательство: ${q.check}`,`Не допускайте: ${q.pitfall}`]},`Выполним перенос на учебную сеть сервисных центров. ${t.caseBrief} Для данного вопроса выделяем только условие: ${q.example} Действие — ${q.decision} Проверяем его так: ${q.check} Сохраняем полученный артефакт вместе с исходными условиями, чтобы другой участник мог повторить проверку. ${q.rule} При объяснении называем действие и доказательство отдельно: название файла или факт создания таблицы сами по себе не заменяют критерий. Теперь сравним правильную и ошибочную ветви.`,[practice],{questions:qna,answer:q.check,estimatedSeconds:120});
  add({id:qid+'-decision',kind:'comparison',title:'Решение и типичная ошибка',visual:{type:'comparison',columns:['Аспект','Обоснованное решение','Рискованный подход'],rows:[['Действие',q.decision,q.pitfall],['Основание',q.rule,'Решение без сверки с условием'],['Доказательство',q.check,'Отсутствие ошибки принимается за полноту проверки']],caption:q.focus}},`Сравним подходы по строкам, не смешивая действие и доказательство. Корректное решение: ${q.decision} Его основание: ${q.rule} Альтернатива из правого столбца — ${q.pitfall} Для нашего примера «${q.example}» она не даёт нужного доказательства: ${q.check} Таблица помогает объяснить выбор; она не вводит дополнительное ограничение вне исходной задачи. Следом отдельно зафиксируем ошибку и способ возврата к корректной проверке.`,[block[4]],{questions:qna});
  add({id:qid+'-warning',kind:'warning',title:'Ошибка и способ исправления',body:q.pitfall,bullets:[q.rule,q.check]},`Ошибка: ${q.pitfall} Вернёмся к смыслу вопроса: ${q.focus} Исправление начинается с правила: ${q.rule} После этого требуется действие: ${q.decision} Завершающий контроль — ${q.check} Изменение без повторной проверки не устраняет неопределённость результата. Для обсуждения используем исходный пример «${q.example}», а не другой случай с удобными условиями. Далее запишем опорные формулировки.`,[block[5]],{questions:qna});
  add({id:qid+'-notebook',kind:'notebook',title:'Запишите',notebook:`${q.title}: ${q.focus}\nПравило: ${q.rule}\nПроверка: ${q.check}`},`Запишем название вопроса «${q.title}» и его смысл: ${q.focus} Затем правило: ${q.rule} Отдельной строкой — признак корректности: ${q.check} Пример для устного пояснения: ${q.example} Эти формулировки уже разобраны; нового условия перед тестом нет. Далее четыре задания проверят решение, правило, название вопроса и связь между элементами разбора.`,[block[6]],{questions:qna,estimatedSeconds:90});
  const explanation=`${q.rule} ${q.decision} Критерий: ${q.check}`;
  const task1={id:qid+'-T01',type:'single',prompt:`Какое решение соответствует разобранному примеру «${q.example}»?`,options:rotate([q.decision,q.pitfall,'Достаточно отсутствия сообщения об ошибке; отдельный контроль результата не нужен.','Можно изменить исходные условия и сохранить прежний вывод без повторной проверки.'].map((text,i)=>({id:'o'+(i+1),text})),li+qi)};
  keys[task1.id]={type:'single',correct:['o1'],explanation,optionExplanations:{o1:q.rule,o2:'Это разобранная ошибка: '+q.pitfall,o3:'Нужен предметный критерий: '+q.check,o4:'Вывод зависит от исходных условий: '+q.example}};
  const task2={id:qid+'-T02',type:'multiple',choose:2,prompt:`Выберите правило выполнения и критерий проверки для вопроса «${q.title}».`,options:rotate([q.rule,q.check,q.pitfall,'Фактические данные можно заменить удобными значениями без фиксации изменений.','Результат не требуется сохранять для повторной проверки.'].map((text,i)=>({id:'o'+(i+1),text})),qi+2)};
  keys[task2.id]={type:'multiple',correct:['o1','o2'],explanation,optionExplanations:{o1:'Разобранное правило действия.',o2:'Разобранный критерий проверки.',o3:'Типичная ошибка, рассмотренная до теста.',o4:'Подмена условий лишает вывод доказательной основы.',o5:'Результат и условия нужны для воспроизведения.'}};
  const task3={id:qid+'-T03',type:'short',prompt:`Как называется вопрос, описанный формулировкой «${q.focus}»? Введите название из блока «Запишите», без номера и кавычек.`};
  keys[task3.id]={type:'short',accepted:[q.title],explanation:`${q.title}: ${q.focus} Регистр и лишние пробелы не учитываются.`};
  const task4={id:qid+'-T04',type:'matching',prompt:'Соотнесите элементы разобранного примера с их ролью. Каждое соответствие используется один раз.',items:['Исходная ситуация','Проектное решение','Критерий проверки','Типичная ошибка'].map((text,i)=>({id:'i'+(i+1),text})),options:rotate([q.example,q.decision,q.check,q.pitfall].map((text,i)=>({id:'o'+(i+1),text})),qi+1)};
  keys[task4.id]={type:'matching',pairs:{i1:'o1',i2:'o2',i3:'o3',i4:'o4'},explanation:`Ситуация: ${q.example} Решение: ${q.decision} Проверка: ${q.check} Ошибка: ${q.pitfall}`};
  for(const [ti,task] of [task1,task2,task3,task4].entries())add({id:task.id+'-slide',kind:'test',title:`Самопроверка ${ti+1} из 4`,task},`${task.prompt} Опора для проверки: ${keys[task.id].explanation} Сначала участники отправляют свой ответ, затем обсуждаем разбор. ${ti===3?`Вопрос завершён. Далее — ${next}.`:'Следующее задание проверяет те же знания в другом формате.'}`,[],{answer:JSON.stringify(keys[task.id],null,2),questions:qna,estimatedSeconds:[60,80,45,100][ti]});
  const current=slides.slice(start);questions.push({lectureId:t.id,questionId:qid,title:q.title,slideIds:current.map(s=>s.id),taskIds:current.filter(s=>s.task).map(s=>s.task.id),evidenceSlideIds:current.filter(s=>!s.task).map(s=>s.id)});
  course.glossary.push({term:q.title,definition:q.focus,slideIds:[qid+'-concept',qid+'-notebook']});
 }
 for(let half=0;half<2;half++)add({id:id('summary-'+half),kind:'summary',title:half?'Итоги · продолжение':'От условий к проверенному артефакту',body:half?undefined:t.objective,bullets:t.questions.slice(half*4,half*4+4).map(q=>`${q.title}: ${q.decision}`)},`Соберём решения вопросов ${half*4+1}–${half*4+4}: ${t.questions.slice(half*4,half*4+4).map(q=>q.decision+' Проверка: '+q.check).join(' ')} Они входят в результат «${t.projectArtifact}». Далее ${half?'связь со следующим занятием':'остальные решения темы'}.`,[old[82]]);
 add({id:id('next'),kind:'summary',title:t.projectArtifact,body:`Следующий шаг: ${t.nextStep}`,bullets:['Сохраните исходные условия, SQL и проверяемые результаты.','Свяжите каждое проектное решение с критерием проверки.']},`Результат занятия — ${t.projectArtifact}. Его ценность в том, что проектные решения можно проверить по исходным условиям. Следующий шаг: ${t.nextStep}. ${t.diagnostic} В ответе теперь можно опираться на разобранные примеры, правила и контроль. Завершим обсуждением вопросов аудитории.`,[old[83]]);
 add({id:id('questions'),kind:'questions',title:'Вопросы от аудитории',body:old[84].body,bullets:old[84].bullets},`Какие вопросы остались по теме «${t.displayTitle}»? ${t.diagnostic} Для ответа сопоставим начало и итог: ${t.questions[0].rule} ${t.questions.at(-1).check} Если сомнение связано с конкретным SQL или данными, сначала назовём исходное условие, затем ожидаемый результат и проверку. ${t.nextStep} — следующий шаг курса.`,[old[84]]);
 for(const s of old.filter(s=>s.kind==='test')){
  const q=questions.filter(q=>q.lectureId===t.id)[s.number-77];const targets=q.taskIds.map(x=>x+'-slide');mapping.push({lectureId:t.id,oldSlide:s.number,oldTitle:s.title,newSlideIds:targets,action:'Итоговый тест заменён блоком четырёх типов самопроверки; исходный тест сохранён в authoring/legacy-deck.ts'});links[t.id][s.number]=targets[0];
 }
 course.lectures.push({id:t.id,title:t.displayTitle,sourceTitle:t.sourceTitle,semester:t.semester,question:t.objective,slides});
 course.curriculum.push({topic:t.sourceTitle,outcome:t.objective,source:`Исходный src/data/courseData.ts: ${t.id}; ${t.lectureHours} лекционных часа; ${t.competencies.join(', ')}. Сведения сохранены из исходника.`,slideIds:slides.filter(s=>!s.task).map(s=>s.id),taskIds:slides.filter(s=>s.task).map(s=>s.task.id)});
 registry.push({id:t.id,title:t.sourceTitle,semester:t.semester,lectureHours:t.lectureHours,competencies:t.competencies,labNumbers:t.labNumbers,slides:slides.length,questions:t.questions.length,tasks:32,estimatedMinutes:Math.round(slides.reduce((n,s)=>n+notes[s.id].estimatedSeconds,0)/60)});
}
const pack={schemaVersion:1,courseId:course.id,contentVersion:version,notes};
write('public/course.json',course);write('public/teacher-notes.json',pack);write('private/teacher-pack.json',pack);
write('public/assessment.json',{schemaVersion:1,courseId:course.id,contentVersion:version,mode:'autonomous-educational',keys});
write('public/legacy-links.json',links);write('authoring/questions.json',questions);write('reports/migration-map.json',mapping);write('reports/registry.json',registry);
fs.writeFileSync('private/teacher.md',course.lectures.map(l=>'# '+l.title+'\n\n'+l.slides.map(s=>`## ${s.title}\n\n${notes[s.id].script}\n\n${notes[s.id].questions}\n\n${notes[s.id].answer}\n`).join('\n')).join('\n'));
console.log({lectures:course.lectures.length,slides:Object.keys(notes).length,tasks:Object.keys(keys).length});
